[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]  # Erreurs de base + imports
ignore = ["E501"]         # Ignorer ligne trop longue

[tool.ruff.format]
quote-style = "double"