name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      
      - name: Install Ruff
        run: pip install ruff==0.14.0
      
      - name: Format Check
        run: ruff format --check app/ tests/
      
      - name: Lint
        run: ruff check app/ tests/

  test:
    runs-on: ubuntu-latest
    needs: check
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Tests
        run: pytest tests/ -v
